# Generated by Django 4.0.4 on 2022-06-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_manufacturer_src_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vga',
            old_name='microwave',
            new_name='memory_bus',
        ),
    ]
