# Generated by Django 4.0.4 on 2022-06-13 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_mainboard_maximun_ram_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu_generation',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.manufacturer'),
        ),
        migrations.AddField(
            model_name='cpu_series',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.manufacturer'),
        ),
    ]
