# Generated by Django 4.0.4 on 2022-06-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_microwave_vga_memory_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ram',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
