# Generated by Django 4.0.4 on 2022-06-13 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_cpu_generation_manufacturer_cpu_series_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu_generation',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.manufacturer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cpu_series',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.manufacturer'),
        ),
    ]
