# Generated by Django 4.0.4 on 2022-06-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_ram_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psu',
            name='psu_power',
        ),
        migrations.AddField(
            model_name='psu',
            name='psu_input_power',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='psu',
            name='psu_wattage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
