# Generated by Django 4.0.4 on 2022-06-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orders_total_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_detail',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
